### PR TITLE
fix(interactive): bump up rustup toolchain version to 1.81.0 to avoid compilation failure

### LINKED ISSUE #4372: [BUG] Interactive rust related CI failure
It seems that the current Interactive Rust-related CI fails due to an indirect dependency upgrading.
https://github.com/alibaba/GraphScope/actions/runs/12387676660/job/34577529616?pr=4343
https://github.com/alibaba/GraphScope/actions/runs/12387676664/job/34577501489?pr=4343

Related PR: https://github.com/alibaba/GraphScope/pull/4343

### PR DESCRIPTION
**Pull request by BingqingLyu**
## Related issue number

Fixes #4372

### CODE REVIEW

**Review by zhanglei1949 — DISMISSED** [review]
LGTM

**Comment by zhanglei1949** [comment]
The workflows runs on self-hosted runners still fails @siyuan0322

**Review by zhanglei1949 — COMMENTED** [review]
LGTM

**Review by zhanglei1949 — APPROVED** [review]
LGTM

**Review by siyuan0322 — APPROVED** [review]

**Pull request merged**
