### PR TITLE
[GAE-Java] Fix : can not compile the submodule of GAE Java SDK

### PR DESCRIPTION
**Pull request by zhanglei1949**
## Related issue number

Fixes

Fix the problem that user can not compile only the submodule of GAE Java SDK

### CODE REVIEW

**Comment by zhanglei1949** [comment]
@lidongze0629 Maybe you need to replace `0.18.0` to the new version when release new version of GraphScope, =。=

**Review by lidongze0629 — APPROVED** [review]

**Comment by yecol** [comment]
> @lidongze0629 Maybe you need to replace `0.18.0` to the new version when release new version of GraphScope, =。=

It would be hard to maintain the GraphScope version number in the `pom` file manually. 
We have a file in the root named VERSION records the current version. Could you get the version from there?

**Review by yecol — CHANGES_REQUESTED** [review]
Please do not assign a version manually.

**Comment by zhanglei1949** [comment]
> > @lidongze0629 Maybe you need to replace `0.18.0` to the new version when release new version of GraphScope, =。=
> 
> It would be hard to maintain the GraphScope version number in the `pom` file manually. We have a file in the root named VERSION records the current version. Could you get the version from there?

I'm not sure whether read project version from file is possible for a maven project, any idea? @sighingnow

**Comment by zhanglei1949** [comment]
- For Source code release, replace `<revision>0.18.0</revision>` to a new version
- For package building and release, the output jars of grape-jdk from `make gae` will use the version specified in `VERSION`

**Review by yecol — APPROVED** [review]

**Pull request merged**
