### PR TITLE
fix(coordinator): Fix coordinator monitor bug

### LINKED ISSUE #3417: [Question]How to set gscoordinator parameters through graphscope.session
want to set
coordinator config  
"monitor":true, 
"monitor_port":9090

```
sess = graphscope.session( cluster_type='hosts',
                           enabled_engines='interactive',
                           vineyard_shared_mem='1Gi',
                           num_workers=1)

```

**log**
```
{
    "solution":"GraphScope One",
    "launcher_type":"hosts",
    "show_log":true,
    "log_level":"DEBUG",
    "session":{
        "num_workers":1,
        "default_local_num_workers":1,
        "reconnect":false,
        "instance_id":"ooxfoa",
        "timeout_seconds":600,
        "dangling_timeout_seconds":600,
        "retry_time_seconds":1,
        "execution_mode":"eager"
    },
    "coordinator":{
        "endpoint":null,
        "service_port":63800,
        "monitor":false,
        "monitor_port":9090,
        "deployment_name":null,
        "node_selector":null,
        "resource":{
            "requests":{
                "cpu":0.5,
                "memory":"512Mi"
            },
            "limits":null
        },
        "operator_mode":false
    },
    "vineyard":{
        "socket":null,
        "rpc_port":9600,
        "deployment_name":null,
        "image":"vineyardcloudnative/vineyardd:latest",
        "resource":{
            "requests":{
                "cpu":0.2,
                "memory":"256Mi"
            },
            "limits":null
        }
    },
    "hosts_launcher":{
        "hosts":[
            "localhost"
        ],
        "etcd":{
            "endpoint":null,
            "listening_client_port":2379,
            "listening_peer_port":2380,
            "replicas":1
        },
        "dataset_download_retries":3
    },
    "kubernetes_launcher":{
        "namespace":null,
        "delete_namespace":false,
        "config_file":null,
        "deployment_mode":"eager",
        "service_type":"NodePort",
        "volumes":null,
        "waiting_for_delete":false,
        "image":{
            "registry":"registry.cn-hongkong.aliyuncs.com",
            "repository":"graphscope",
            "tag":"0.26.0",
            "pull_secrets":[

            ],
            "pull_policy":"IfNotPresent"
        },
        "engine":{
            "enabled_engines":"interactive",
            "node_selector":null,
            "enable_gae":false,
            "enable_gae_java":false,
            "enable_gie":false,
            "enable_gle":false,
            "preemptive":true,
            "gae_resource":{
                "requests":{
                    "cpu":1,
                    "memory":"4Gi"
                },
                "limits":null
            },
            "gie_executor_resource":{
                "requests":{
                    "cpu":1,
                    "memory":"2Gi"
                },
                "limits":null
            },
            "gie_frontend_resource":{
                "requests":{
                    "cpu":0.5,
                    "memory":"1Gi"
                },
                "limits":null
            },
            "gle_resource":{
                "requests":{
                    "cpu":0.2,
                    "memory":"1Gi"
                },
                "limits":null
            }
        },
        "dataset":{
            "enable":false,
            "proxy":null
        },
        "mars":{
            "enable":false,
            "worker_resource":{
                "requests":{
                    "cpu":0.2,
                    "memory":"4Mi"
                },
                "limits":null
            },
            "scheduler_resource":{
                "requests":{
                    "cpu":0.2,
                    "memory":"4Mi"
                },
                "limits":null
            }
        }
    },
    "operator_launcher":{
        "namespace":"default",
        "gae_endpoint":"",
        "hosts":[

        ]
    }
}

```

**Environment (please complete the following information):**
 - GraphScope version:  master
 - OS:  Linux

### PR DESCRIPTION
**Pull request by JackyYangPassion**
## Related issue number

Fixes #3417

### CODE REVIEW

**Review by siyuan0322 — DISMISSED** [review]

**Comment by siyuan0322** [comment]
Most CI failed because the self-hosted runner is disabled for security reasons, so don't worry about it.

**Comment by siyuan0322** [comment]
And please sign the CLA :)

**Comment by JackyYangPassion** [comment]
> And please sign the CLA :)
Done！
from this PR #3328  I remember I signed the CLA. Do I need to sign it every time I submit it?

**Comment by siyuan0322** [comment]
> > And please sign the CLA :)
> 
> Done！ from this PR #3389 I remember I signed the CLA. Do I need to sign it every time I submit it?

No, you doesn't. I see that you used a different email for commit this time.

**Comment by siyuan0322** [comment]
Format is still breaking. I recommend you to use black (same version as the ci) to format the code for you

**Comment by JackyYangPassion** [comment]
> > > And please sign the CLA :)
> > 
> > 
> > Done！ from this PR #3389 I remember I signed the CLA. Do I need to sign it every time I submit it?
> 
> No, you doesn't. I see that you used a different email for commit this time.

Thanks for the feedback, I saw it

**Pull request merged**
