### PR TITLE
fix(analytical): fix the louvain algorithm that the result is not consistent with #183

### LINKED ISSUE #3457: [BUG] Run louvain algo on k8s error
**Describe the bug**
Run louvain algo there is some error

**To Reproduce**

**run louvain**

```
graph = session.g(oid_type="string",generate_eid=True,directed=False)
####################################################################
#Louvain算法
print("开始运行 Louvain 算法")
result_louvain = graphscope.louvain(graph, min_progress=1000, progress_tries=1)
#格式整理
dataframe_louvain = result_louvain.to_dataframe({"node": "v.id", "result": "r"})
print("算法运行结束！")
```

**error log**

```
Consolidate compiler generated dependencies of target 5bd82f1167356c336b6d76a64a6391048f8a717871f46092e024df869e6f2c3a
[ 50%] Building CXX object CMakeFiles/5bd82f1167356c336b6d76a64a6391048f8a717871f46092e024df869e6f2c3a.dir/opt/graphscope/include/graphscope/frame/app_frame.cc.o
In file included from /opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_app_base.h:31,
                 from /opt/graphscope/include/graphscope/frame/app_frame.cc:43:
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h: In instantiation of 'void gs::PregelLouvain<FRAG_T>::Init(gs::PregelLouvain<FRAG_T>::pregel_vertex_t&, gs::PregelLouvain<FRAG_T>::compute_context_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::PregelLouvain<FRAG_T>::pregel_vertex_t = gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; gs::PregelLouvain<FRAG_T>::compute_context_t = gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >]':
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_app_base.h:98:26:   required from 'void gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::PEval(const fragment_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; VERTEX_PROGRAM_T = gs::PregelLouvain<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t = gs::LouvainContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> > >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t = grape::ParallelMessageManager]'
/opt/vineyard/include/grape/worker/worker.h:158:16:   required from 'typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type grape::Worker<APP_T, MESSAGE_MANAGER_T>::runPEval() [with T = grape::ParallelMessageManager; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager; typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type = void; typename APP_T::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>]'
/opt/vineyard/include/grape/worker/worker.h:102:13:   required from 'void grape::Worker<APP_T, MESSAGE_MANAGER_T>::Query(Args&& ...) [with Args = {int, int}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:191:18:   required from 'static void gs::AppInvoker<APP_T>::query_impl(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&, std::index_sequence<__var_indices ...>) [with long unsigned int ...I = {0, 1}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>; std::index_sequence<__var_indices ...> = std::integer_sequence<long unsigned int, 0, 1>]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:205:15:   required from 'static boost::leaf::result<std::nullptr_t> gs::AppInvoker<APP_T>::Query(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&) [with APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>]'
/opt/graphscope/include/graphscope/frame/app_frame.cc:91:44:   required from here
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:78:22: error: invalid 'static_cast' from type 'grape::EmptyType' to type 'gs::PregelLouvain<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >::edata_t' {aka 'float'}
   78 |       sigma_total += static_cast<edata_t>(e.get_data());
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h: In instantiation of 'void gs::PregelLouvain<FRAG_T>::getAndSendCommunityInfo(gs::PregelLouvain<FRAG_T>::pregel_vertex_t&, gs::PregelLouvain<FRAG_T>::compute_context_t&, const grape::IteratorPair<gs::LouvainMessage<typename FRAG_T::vid_t>*>&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::PregelLouvain<FRAG_T>::pregel_vertex_t = gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; gs::PregelLouvain<FRAG_T>::compute_context_t = gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; typename FRAG_T::vid_t = long unsigned int]':
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:154:7:   required from 'void gs::PregelLouvain<FRAG_T>::Compute(grape::IteratorPair<gs::LouvainMessage<typename FRAG_T::vid_t>*>, gs::PregelLouvain<FRAG_T>::pregel_vertex_t&, gs::PregelLouvain<FRAG_T>::compute_context_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; typename FRAG_T::vid_t = long unsigned int; gs::PregelLouvain<FRAG_T>::pregel_vertex_t = gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; gs::PregelLouvain<FRAG_T>::compute_context_t = gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >]'
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_app_base.h:110:37:   required from 'void gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::PEval(const fragment_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; VERTEX_PROGRAM_T = gs::PregelLouvain<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t = gs::LouvainContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> > >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t = grape::ParallelMessageManager]'
/opt/vineyard/include/grape/worker/worker.h:158:16:   required from 'typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type grape::Worker<APP_T, MESSAGE_MANAGER_T>::runPEval() [with T = grape::ParallelMessageManager; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager; typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type = void; typename APP_T::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>]'
/opt/vineyard/include/grape/worker/worker.h:102:13:   required from 'void grape::Worker<APP_T, MESSAGE_MANAGER_T>::Query(Args&& ...) [with Args = {int, int}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:191:18:   required from 'static void gs::AppInvoker<APP_T>::query_impl(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&, std::index_sequence<__var_indices ...>) [with long unsigned int ...I = {0, 1}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>; std::index_sequence<__var_indices ...> = std::integer_sequence<long unsigned int, 0, 1>]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:205:15:   required from 'static boost::leaf::result<std::nullptr_t> gs::AppInvoker<APP_T>::Query(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&) [with APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>]'
/opt/graphscope/include/graphscope/frame/app_frame.cc:91:44:   required from here
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:215:35: error: invalid 'static_cast' from type 'grape::EmptyType' to type 'gs::PregelLouvain<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >::edata_t' {aka 'float'}
  215 |         out_message.edge_weight = static_cast<edata_t>(edge.get_data());
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:25,
                 from /opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_app_base.h:31,
                 from /opt/graphscope/include/graphscope/frame/app_frame.cc:43:
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_vertex.h: In instantiation of 'gs::LouvainVertex<FRAG_T, VD_T, MD_T>::edata_t gs::LouvainVertex<FRAG_T, VD_T, MD_T>::get_edge_values(const std::set<typename FRAG_T::vid_t>&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; VD_T = std::__cxx11::basic_string<char>; MD_T = gs::LouvainMessage<long unsigned int>; gs::LouvainVertex<FRAG_T, VD_T, MD_T>::edata_t = float; typename FRAG_T::vid_t = long unsigned int; typename FRAG_T::vid_t = long unsigned int]':
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:350:37:   required from 'double gs::PregelLouvain<FRAG_T>::calculateActualQuality(gs::PregelLouvain<FRAG_T>::pregel_vertex_t&, gs::PregelLouvain<FRAG_T>::compute_context_t&, const grape::IteratorPair<gs::LouvainMessage<typename FRAG_T::vid_t>*>&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::PregelLouvain<FRAG_T>::pregel_vertex_t = gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; gs::PregelLouvain<FRAG_T>::compute_context_t = gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; typename FRAG_T::vid_t = long unsigned int]'
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain.h:133:16:   required from 'void gs::PregelLouvain<FRAG_T>::Compute(grape::IteratorPair<gs::LouvainMessage<typename FRAG_T::vid_t>*>, gs::PregelLouvain<FRAG_T>::pregel_vertex_t&, gs::PregelLouvain<FRAG_T>::compute_context_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; typename FRAG_T::vid_t = long unsigned int; gs::PregelLouvain<FRAG_T>::pregel_vertex_t = gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >; gs::PregelLouvain<FRAG_T>::compute_context_t = gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >]'
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_app_base.h:110:37:   required from 'void gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::PEval(const fragment_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t&, gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t&) [with FRAG_T = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; VERTEX_PROGRAM_T = gs::PregelLouvain<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::context_t = gs::LouvainContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, gs::PregelComputeContext<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> > >; gs::LouvainAppBase<FRAG_T, VERTEX_PROGRAM_T>::message_manager_t = grape::ParallelMessageManager]'
/opt/vineyard/include/grape/worker/worker.h:158:16:   required from 'typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type grape::Worker<APP_T, MESSAGE_MANAGER_T>::runPEval() [with T = grape::ParallelMessageManager; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager; typename std::enable_if<(! std::is_same<T, grape::AutoParallelMessageManager<typename APP_T::fragment_t> >::value)>::type = void; typename APP_T::fragment_t = gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>]'
/opt/vineyard/include/grape/worker/worker.h:102:13:   required from 'void grape::Worker<APP_T, MESSAGE_MANAGER_T>::Query(Args&& ...) [with Args = {int, int}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; MESSAGE_MANAGER_T = grape::ParallelMessageManager]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:191:18:   required from 'static void gs::AppInvoker<APP_T>::query_impl(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&, std::index_sequence<__var_indices ...>) [with long unsigned int ...I = {0, 1}; APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>; std::index_sequence<__var_indices ...> = std::integer_sequence<long unsigned int, 0, 1>]'
/opt/graphscope/include/graphscope/core/app/app_invoker.h:205:15:   required from 'static boost::leaf::result<std::nullptr_t> gs::AppInvoker<APP_T>::Query(std::shared_ptr<typename APP_T::worker_t>, const gs::rpc::QueryArgs&) [with APP_T = gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >; typename APP_T::worker_t = grape::Worker<gs::LouvainAppBase<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false> >, grape::ParallelMessageManager>]'
/opt/graphscope/include/graphscope/frame/app_frame.cc:91:44:   required from here
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_vertex.h:123:18: error: invalid 'static_cast' from type 'grape::EmptyType' to type 'gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >::edata_t' {aka 'float'}
  123 |           ret += static_cast<edata_t>(edge.get_data());
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/graphscope/include/graphscope/apps/pregel/louvain/louvain_vertex.h:129:18: error: invalid 'static_cast' from type 'grape::EmptyType' to type 'gs::LouvainVertex<gs::ArrowProjectedFragment<std::__cxx11::basic_string<char>, long unsigned int, grape::EmptyType, grape::EmptyType, vineyard::ArrowVertexMap<std::basic_string_view<char>, long unsigned int>, false>, std::__cxx11::basic_string<char>, gs::LouvainMessage<long unsigned int> >::edata_t' {aka 'float'}
  129 |           ret += static_cast<edata_t>(edge.get_data());
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option '-Wno-unused-lambda-capture' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-undef-prefix' may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/5bd82f1167356c336b6d76a64a6391048f8a717871f46092e024df869e6f2c3a.dir/build.make:76: CMakeFiles/5bd82f1167356c336b6d76a64a6391048f8a717871f46092e024df869e6f2c3a.dir/opt/graphscope/include/graphscope/frame/app_frame.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/5bd82f1167356c336b6d76a64a6391048f8a717871f46092e024df869e6f2c3a.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Environment (please complete the following information):**
 - GraphScope version:v0.25.0
 - OS: Linux
 - Kubernetes Version 1.23
 - python 3.7

### PR DESCRIPTION
**Pull request by acezen**
## What do these changes do?

This change try to fix the louvain algorithm that the result is not consistent with #183

## Related issue number

Close #3457

### CODE REVIEW

**Comment by JackyYangPassion** [comment]
unit test 

```
FAILED ../../../.local/lib/python3.8/site-packages/graphscope/tests/unittest/test_app.py::test_other_app_on_undirected_graph - assert 10733 == 103

```

**Comment by acezen** [comment]
> unit test #3474
> 
> expect 103 community but 10733
> 
> ```
> FAILED ../../../.local/lib/python3.8/site-packages/graphscope/tests/unittest/test_app.py::test_other_app_on_undirected_graph - assert 10733 == 103
> ```

Yes, there are still something wrong, trying to figure out

**Comment by acezen** [comment]
> unit test #3474
> 
> expect 103 community but 10733
> 
> ```
> FAILED ../../../.local/lib/python3.8/site-packages/graphscope/tests/unittest/test_app.py::test_other_app_on_undirected_graph - assert 10733 == 103
> ```

I know the problem, it seems that we need to do a `wcc` to the louvain result and them get the real community result...

**Comment by JackyYangPassion** [comment]
> > unit test #3474
> > expect 103 community but 10733
> > ```
> > FAILED ../../../.local/lib/python3.8/site-packages/graphscope/tests/unittest/test_app.py::test_other_app_on_undirected_graph - assert 10733 == 103
> > ```
> 
> I find the real problem for that, it seems that we need to do a `wcc` to the louvain result and then get the real community result... since the community id in graphscope can represent by any of the id in the community.

Very cool. @acezen  Can you provide the logic for subsequent processing? I can verify it based on test data. I have been watching GAE for the past two days based on the PIE model, trying to find the root cause in a difficult way.

**Comment by acezen** [comment]
> > > unit test #3474
> > > expect 103 community but 10733
> > > ```
> > > FAILED ../../../.local/lib/python3.8/site-packages/graphscope/tests/unittest/test_app.py::test_other_app_on_undirected_graph - assert 10733 == 103
> > > ```
> > 
> > 
> > I find the real problem for that, it seems that we need to do a `wcc` to the louvain result and then get the real community result... since the community id in graphscope can represent by any of the id in the community.
> 
> Very cool. @acezen Can you provide the logic for subsequent processing? I can verify it based on test data. I have been watching GAE for the past two days based on the PIE model, trying to find the root cause in a difficult way.

later I will push a commit that output the correct result of Lovain, then it should not need user to do the union find.

**Comment by acezen** [comment]
hi, @shirly121, the `test_gremlin_timeout` failed in CI, can you help look at the reason for the failure?
https://github.com/alibaba/GraphScope/actions/runs/7496630317/job/20409902909?pr=3472

**Review by siyuan0322 — APPROVED** [review]

**Review by lidongze0629 — APPROVED** [review]

**Pull request merged**
