### PR TITLE
Store ffi for GNN

### LINKED ISSUE #637: store ffi for GNN
as titled

### PR DESCRIPTION
**Pull request by tianliplus**
## What do these changes do?

add store ffi for gnn

## Related issue number

Fixes #637

### CODE REVIEW

**Comment by LiSu** [comment]
Looks fine to me, @GoldenLeaves please have a look of this PR.

**Review by GoldenLeaves — APPROVED** [review]
fine

**Review by GoldenLeaves — CHANGES_REQUESTED** [review]
errors to be fixed

**Review by GoldenLeaves — APPROVED** [review]
Looks fine

**Pull request merged**
