### PR TITLE
check docker is running or not in prepare_env.sh

### LINKED ISSUE #12: [BUG] run the environment preparing script will delete exist docker
**Describe the bug**
# run the environment preparing script.
./scripts/prepare_env.sh
During running this script will delete my existing docker instance, without warning or checking if docker exists. 
Really confused.

### PR DESCRIPTION
**Pull request by acezen**
## What do these changes do?
- check docker is running in prepare_env.sh

## Related issue number

Fixes #12

### CODE REVIEW

**Review by sighingnow — APPROVED** [review]

**Comment by sighingnow** [comment]
Will this PR fix issue #12 ?

**Comment by acezen** [comment]
> Will this PR fix issue #12 ?

yes, this pr add a check that docker is running or not. if not, we start the docker daemon.

**Review by sighingnow — COMMENTED** [review]
The `cp -n` may not work. Every `minikube start` will generate a new config. The python kubernetes client cannot work as expected if the config file doesn't get updated.

**Comment by sighingnow** [comment]
> The `cp -n` may not work. Every `minikube start` will generate a new config. The python kubernetes client cannot work as expected if the config file doesn't get updated.

Could we do the following things at the begin of `prepare_env{_wsl}.sh` ?
```
if [ -f "${HOME}/.kube/config"];
then
    echo "We found existing kubernetes config, seems that you already have a ready kubernetes cluster"
    echo "WARNING: If you do want to reset the kubernetes environment, please delete the existing config by"
    echo ""
    echo "    rm -rf ${HOME}/.kube"
    echo ""
    echo "and retry this script again."
    exit 0
fi
```

**Comment by sighingnow** [comment]
@yecol I want to know your comment on this PR.

**Review by yecol — APPROVED** [review]
LGTM

**Pull request merged**
