### PR TITLE
Update rust toolchain to latest 1.62.0

### PR DESCRIPTION
**Pull request by siyuan0322**
See if the buffer underflow error is still exists.

### CODE REVIEW

**Comment by longbinlai** [comment]
Can merge the main branch to see if this has been fixed. @siyuan0322

**Comment by siyuan0322** [comment]
> Can merge the main branch to see if this has been fixed. @siyuan0322

Merged the main and it's still failing.

**Comment by longbinlai** [comment]
Can merge main to try again? @siyuan0322

**Comment by siyuan0322** [comment]
Closed as resolved by #2376

**Pull request closed without merging**
