### PR TITLE
fix(analytical): make clustering support undirected graph

### LINKED ISSUE #3711: [BUG] wrong result of clustering function
**Describe the bug**
I use `nx.clustering(G)` to compute the clustering coefficient value. But the result is wrong (even negative).

**To Reproduce**
```python
import graphscope
import graphscope.nx as nx
# import networkx as nx

G = nx.Graph()
G.add_nodes_from([1,2,3])
G.add_edges_from([(1,2),(2,3),(3,1)])
print(nx.clustering(G))
print(nx.average_clustering(G))
```
the result is
```
{1: -4.0, 2: -4.0, 3: -4.0}
-4.0
```
but expected result is
```
{1: 1.0, 2: 1.0, 3: 1.0}
1.0
```

**Screenshots**
image

**Environment (please complete the following information):**
 - GraphScope version: 0.27.0
 - OS: Linux
 - Version: Red Hat 4.8.5-44

### PR DESCRIPTION
**Pull request by acezen**
## What do these changes do?
see #3711 

## Related issue number

Fixes #3711

### CODE REVIEW

**Comment by acezen** [comment]
hi, @doudoubobo, I have a question about the computational formula of clustering:
- in NetworkX the formula is 
`[2 * T(v) / deg(v)*(deg(v) - 1)](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cluster.clustering.html#networkx.algorithms.cluster.clustering)` 
but why our formula is `[T(v) / deg(v)*(deg(v)-1](https://github.com/alibaba/GraphScope/blob/4a7e1ab8559024c20090c1866e54f690f451c084/analytical_engine/apps/clustering/clustering.h#L254)`?

- what's the meaning and use of `rec_degree` in https://github.com/alibaba/GraphScope/blob/4a7e1ab8559024c20090c1866e54f690f451c084/analytical_engine/apps/clustering/clustering.h#L253 ?

**Comment by doudoubobo** [comment]
> hi, @doudoubobo, I have a question about the computational formula of clustering:
> 
> * in NetworkX the formula is
>   `[2 * T(v) / deg(v)*(deg(v) - 1)]` in
>   https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cluster.clustering.html#networkx.algorithms.cluster.clustering
>   but why our formula is `[T(v) / deg(v)*(deg(v)-1]`
>   https://github.com/alibaba/GraphScope/blob/4a7e1ab8559024c20090c1866e54f690f451c084/analytical_engine/apps/clustering/clustering.h#L254
>   ?
> * what's the meaning and use of `rec_degree` in https://github.com/alibaba/GraphScope/blob/4a7e1ab8559024c20090c1866e54f690f451c084/analytical_engine/apps/clustering/clustering.h#L253

Q: why our formula is [T(v) / deg(v)*(deg(v)-1]?
A: In the implement method of triangle counting, I remember the real triangle counting number for undirected graph is 2.0 * T(v) and 1.0 * T(v) for directed graph (see https://en.wikipedia.org/wiki/Clustering_coefficient)

Q: what's the meaning and use of `rec_degree`?
A: See https://en.wikipedia.org/wiki/Clustering_coefficient, the `k_i` is defined as the neighbor number of a vertex. For a directed graph, if both `src-->dst` and `dst-->src` edges exist, the degree of `src` is 2 but the `k_i` is 1. `rec_degree` is used to handle such situation.

**Review by doudoubobo — APPROVED** [review]

**Comment by doudoubobo** [comment]
> hi, @doudoubobo, since GraphScope only allow one `MessageStrategy` in one application:
> 
> https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/clustering.h#L47-L48
> 
> for undirected graph, the strategy should be `kAlongOutgoingEdgeToOuterVertex` and use `SendMsgThroughOEdges` to send message like `triangle`:
> 
> https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/triangles.h#L51-L53
> 
> But for the reason above, I use `SendMsgThroughEdges` for both directed graph and undirected graph, and the test case is ok to pass.
> 
> https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/clustering.h#L62-L63
> 
> Can you help me double check that `SendMsgThroughEdges` is ok for directed graph and undirected graph in the message passing between fragments? I don't want to bring another potential bug with the changes.

For directed graph, since we set `message_strategy = grape::MessageStrategy::kAlongEdgeToOuterVertex`, `SendMsgThroughOEdges` and `SendMsgThroughEdges` should behave the same. Same for undirected graphs.

**Comment by acezen** [comment]
> > hi, @doudoubobo, since GraphScope only allow one `MessageStrategy` in one application:
> > https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/clustering.h#L47-L48
> > 
> > for undirected graph, the strategy should be `kAlongOutgoingEdgeToOuterVertex` and use `SendMsgThroughOEdges` to send message like `triangle`:
> > https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/triangles.h#L51-L53
> > 
> > But for the reason above, I use `SendMsgThroughEdges` for both directed graph and undirected graph, and the test case is ok to pass.
> > https://github.com/alibaba/GraphScope/blob/988aa469b55203254dbb7aa7784862f0876c08fe/analytical_engine/apps/clustering/clustering.h#L62-L63
> > 
> > Can you help me double check that `SendMsgThroughEdges` is ok for directed graph and undirected graph in the message passing between fragments? I don't want to bring another potential bug with the changes.
> 
> For directed graph, since we set `message_strategy = grape::MessageStrategy::kAlongEdgeToOuterVertex`, `SendMsgThroughOEdges` and `SendMsgThroughEdges` should behave the same. Same for undirected graphs.

thanks for the reply, since the approve dismiss by the fix push, can yo approve again to the PR.

**Review by siyuan0322 — APPROVED** [review]

**Review by doudoubobo — APPROVED** [review]

**Pull request merged**
