### PR TITLE
Update getting_started.md

### PR DESCRIPTION
**Pull request by haohao0103**
graphscope.interactive(g)  
this method will get an error,  the method may not be defined; I tried graphscope.gremlin(g),this can works。

ps: I am not very familiar with python, if there are other more reasonable modification plan, please let me know, thanks!

## Related issue number

Fixes

### CODE REVIEW

**Comment by haohao0103** [comment]
sorry,I can see why. It's because my pip install graphscope can only install up to version 0.21, so graphScope.interactive (g) gives me an error.

**Comment by haohao0103** [comment]
> sorry,I can see why. It's because my pip install graphscope can only install up to version 0.21, so graphScope.interactive (g) gives me an error.

My system is mac os, when I run pip to check the installable graphscope version, the latest version is only 0.21. Do we no longer support mac os? thanks

**Comment by sighingnow** [comment]
> > sorry,I can see why. It's because my pip install graphscope can only install up to version 0.21, so graphScope.interactive (g) gives me an error.
> 
> My system is mac os, when I run pip to check the installable graphscope version, the latest version is only 0.21. Do we no longer support mac os? thanks

Recently, releases of Graphscope require macOS 12+ for both Intel and Apple Silicon.

**Comment by haohao0103** [comment]
> > > sorry,I can see why. It's because my pip install graphscope can only install up to version 0.21, so graphScope.interactive (g) gives me an error.
> > 
> > 
> > My system is mac os, when I run pip to check the installable graphscope version, the latest version is only 0.21. Do we no longer support mac os? thanks
> 
> Recent releases of GraphScope require macOS 12+ for both Intel and Apple Silicon.
Thanks for your response,My environments are as follows:
macOS: 14.1.2 (23B92)，
Python: 3.9,
pip: 23.3.2；

My co-worker also uses macos, but it's version 12.x. He can install graphscope 0.25. Is it because my macos version is too high? thanks

**Comment by haohao0103** [comment]
Thanks for your response,My environments are as follows:
macOS: 14.1.2 (23B92)，
cpu:Intel Core i5,
Python: 3.9,
pip: 23.3.2；

My co-worker also uses macos, but it's version 12.x. He can install graphscope 0.25. Is it because my macos version is too high? thanks

**Comment by sighingnow** [comment]
May I know your error message when `pip3 install graphscope` failed?

**Comment by haohao0103** [comment]
> May I know your error message when `pip3 install graphscope` failed?

It won't fail when I install it, it's just that it can only install up to 0.21：
image

**Comment by sighingnow** [comment]
Are you working with Apple's default Python or the installer downloaded from https://www.python.org/downloads/release ? It is known that these Python packages can only support old ABIs even you have upgraded your OS.

Please try with the Python installed by homebrew.

To check the compatible OS version of your Python environment, try:

```bash
python3 -c "print(open('/System/Library/CoreServices/SystemVersion.plist').read())"
```

**Comment by haohao0103** [comment]
> Are you working with Apple's default Python or the installer downloaded from https://www.python.org/downloads/release ? It is known that these Python packages can only support old ABIs even you have upgraded your OS.
> 
> Please try with the Python installed by homebrew.
> 
> To check the compatible OS version of your Python environment, try:
> 
> ```shell
> python3 -c "print(open('/System/Library/CoreServices/SystemVersion.plist').read())"
> ```

thanks,I followed your advice. with Apple's default Python, it can works. I used to use miniconda, now it seems that miniconda is the cause. thanks again!!!

**Pull request closed without merging**
