### PR TITLE
[Bug fix] fix delete fragment failed when unloading graph

### PR DESCRIPTION
**Pull request by songqing**
## What do these changes do?

When unloading graph, the current logic is deleting fragment group first and then deleting the corresponding fragments.
However, deleting fragment group will also deleting the corresponding fragments automatically as we use the param "deep", then when we delete the fragments of the group, they don't exist and that will cause core dump when compiling graph_engine with "Debug" option.
g2

So, remove the logic of deleting fragments to solve the problem.

## Related issue number

This bug can be recurrent when running the python unittest  "project_to_simple_with_name" in "tests/unittest/test_graph.py"

### CODE REVIEW

**Comment by sighingnow** [comment]
Hi @songqing,

Thanks for raising this issue up!

Which version of graphscope you are working with?

**Comment by sighingnow** [comment]
I believe the issue has already been fixed in vineyard in https://github.com/v6d-io/v6d/pull/1067, which, has already been included in vineyard>=v0.11.0.

We encourage to upgrade vineyard to either v0.11.0 or v0.11.1 for the fixes. If you are working with "main" branch of graphscope, just install our latest vineyard release v0.11.3.

Thanks!

**Comment by songqing** [comment]
> 

The GraphScope version I used is 0.17.0.

**Comment by songqing** [comment]
OK, the fix in v6d may not cause the graph_engine process core dump again when unloading graph, but the problem I mentioned still exists.

**Comment by sighingnow** [comment]
The duplicated call for "DelData" is to guarantee the graph been dropped when unloading graph. We did have encountered some corner cases where the graph is failed to remove from memory if we only delete "frag_group_id".

Ideally `DelData()` on an non-exist object should casuing nothing.

**Comment by songqing** [comment]
ok, I see, how about adding a check if the fragment exist, then delete it?

**Comment by sighingnow** [comment]
> ok, I see, how about adding a check if the fragment exist, then delete it?

DelData = if exists then delete else noop

**Comment by songqing** [comment]
> > ok, I see, how about adding a check if the fragment exist, then delete it?
> 
> DelData = if exists then delete else noop

OK, that's good, I'll close this PR, thank you.

**Comment by sighingnow** [comment]
> OK, that's good, I'll close this PR, thank you.

Thanks for being interested in GraphScope! Feel free to open issues or pull requests if you have any further question!

**Comment by sighingnow** [comment]
Closing, as discussed.

**Pull request closed without merging**
