### PR TITLE
fix(interactive): Fix typo in cypher query examples

### PR DESCRIPTION
**Pull request by jsoref**
## What do these changes do?

Fixes spelling errors in cypher files per https://github.com/alibaba/GraphScope/pull/3547#issuecomment-1950933992

### CODE REVIEW

**Comment by sighingnow** [comment]
/ping @liulx20 and @zhanglei1949 could you folks take a look on this cypher query changes?

Thanks!

**Comment by zhanglei1949** [comment]
Thanks! LGTM!

**Comment by zhanglei1949** [comment]
@acezen Could you please check the changes to nx part?

**Review by acezen — APPROVED** [review]
LGTM

**Pull request merged**
